version: '3.2'

services:
  keycloak:
    container_name: keycloak
    image: ghcr.io/pausegarra/auth:${VERSION}
    command: --hostname=https://auth.pausegarra.es --http-enabled=true
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 1G
          cpus: '0.5'
    ports:
      - "8097:8080"
      - "8098:9000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - KC_DB_USERNAME=${DB_USERNAME}
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KC_DB_URL=jdbc:postgresql://host.docker.internal:5432/my_keycloak
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
