version: '3.2'

services:
  keycloak:
    container_name: my-keycloak
    image: ghcr.io/pausegarra/auth:${VERSION}
    ports:
      - "8097:8080"
      - "8098:9000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - KC_DB=postgres
      - KC_PROXY=edge
      - KC_DB_USERNAME=${DB_USERNAME}
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KC_DB_URL=jdbc:postgresql://host.docker.internal:5432/admin_keycloak
      - KC_HOSTNAME=auth.pausegarra.es